name: Publish release tarball
on:
  push:
    tags:
      - 'v*.*'

jobs:
  publish:
    name: Publish release tarball
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: logiops-${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Add version info
        run: echo ${{ github.ref_name }} > version.txt

      - name: Remove git repo info
        run: find . -name '.git' | xargs rm -rf

      - name: Create tarball
        run: |
          find * -type f| tar caf /tmp/$ARCHIVE_NAME.tar.gz \
            --xform s:^:$ARCHIVE_NAME/: --verbatim-files-from -T-
          mv /tmp/$ARCHIVE_NAME.tar.gz .

      - name: Upload release asset
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: logiops-${{ github.ref_name }}.tar.gz
